name: CI/CD Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Get Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Build Docker Image
      - name: Build Docker Image
        run: docker build -t myapp .

      # 3. Run Container
      - name: Run Container
        run: docker run -d -p 3000:3000 myapp

      # 4. Check Running Container
      - name: List Containers
        run: docker ps
